name: Maluma
favicon: null
layout_spectrum: 0.6502530565485358
typography_spectrum: 0.9165602843277156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.40426409197971225
  lightness: 0.32826122734695673
  saturation: 0.572951901005581
  rhythmicContrast: 0.0330626405775547
purpose: []
